name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Build, run, and test (Docker Compose)
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: |
          docker compose -f docker-compose.yml build

      - name: Start stack
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for API health
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8000/healthz >/dev/null; then
              echo "API is healthy"; exit 0;
            fi
            sleep 1
          done
          echo "API did not become healthy in time" >&2
          docker compose ps
          exit 1

      - name: Run tests inside API container
        run: |
          CID=$(docker compose ps -q api)
          docker cp tests "$CID":/app/
          docker compose exec -T api python -m pytest -q /app/tests

      - name: Dump docker status
        if: always()
        run: |
            docker compose ps > compose-ps.txt
            docker compose logs --no-color > compose-logs.txt || true
            docker compose logs --no-color api > api.log || true
            docker compose logs --no-color worker > worker.log || true
            docker compose logs --no-color db > db.log || true
            docker compose logs --no-color redis > redis.log || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: docker-logs
            path: |
                compose-ps.txt
                compose-logs.txt
                api.log
                worker.log
                db.log
                redis.log

      - name: Stop stack
        if: always()
        run: |
            docker compose down -v
